version: 0.2

env:
  variables:
    TEMPLATE_FILE: "template.yml"
    OUTPUT_FILE: "outputtemplate.yml"
    BUCKET: "dsb-test-pipeline-output-bucket"

phases:
 install:
  - echo "'install' phase started on $(date)"
  runtime-versions:
   python: 3.7
 build: 
  commands:
   - pip install --target ./package -r ./src/requirements.txt
   - sam build
   - sam package --s3-bucket ${BUCKET} --output-template-file ${OUTPUT_FILE}
   
artifacts:
 type: zip
 files:
  - ${TEMPLATE_FILE}
  - ${OUTPUT_FILE}